//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tms_wb_ui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tms_wb_ui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Icon CRA_TinyManagemntSystem_ICONSET {
            get {
                object obj = ResourceManager.GetObject("CRA_TinyManagemntSystem_ICONSET", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img3 {
            get {
                object obj = ResourceManager.GetObject("img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap spl1 {
            get {
                object obj = ResourceManager.GetObject("spl1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap spl2 {
            get {
                object obj = ResourceManager.GetObject("spl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA SoftSystems Prvt Ltd..
        /// </summary>
        public static string STRING_COMPANY {
            get {
                return ResourceManager.GetString("STRING_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to make changes in your database with these information?.
        /// </summary>
        public static string STRING_CONFIRM_MSG {
            get {
                return ResourceManager.GetString("STRING_CONFIRM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm : TinyManagementSystem..
        /// </summary>
        public static string STRING_CONFIRM_REG_MSG_CAPTION {
            get {
                return ResourceManager.GetString("STRING_CONFIRM_REG_MSG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Poduct is for Educational Porpose. Any unauthorised comerical practice will be considered as illegal practice and will be subjected to Judiciary Punishments. All Rights are Reserver. CopyRight (C) 2011..
        /// </summary>
        public static string STRING_DISCLAIMER {
            get {
                return ResourceManager.GetString("STRING_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any of the fields might be left. Fill those!.
        /// </summary>
        public static string STRING_FILL_ALL_FIELDS {
            get {
                return ResourceManager.GetString("STRING_FILL_ALL_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing..
        /// </summary>
        public static string STRING_INIT {
            get {
                return ResourceManager.GetString("STRING_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS : CRA TinyManagementSystem.
        /// </summary>
        public static string STRING_MSG_CAPTION {
            get {
                return ResourceManager.GetString("STRING_MSG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR : CRA TinyManagementSystem.
        /// </summary>
        public static string STRING_MSG_CAPTION_ERROR {
            get {
                return ResourceManager.GetString("STRING_MSG_CAPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is update or inserted SUCCESSFULLY on your Database!.
        /// </summary>
        public static string STRING_MSG_SUCCESS {
            get {
                return ResourceManager.GetString("STRING_MSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyManagementSystem.
        /// </summary>
        public static string STRING_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("STRING_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Or might be something went wrong with this application. Please notify to the respected company about this bug..
        /// </summary>
        public static string STRING_UNHANDLED_MSG {
            get {
                return ResourceManager.GetString("STRING_UNHANDLED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        public static string STRING_VERSION {
            get {
                return ResourceManager.GetString("STRING_VERSION", resourceCulture);
            }
        }
    }
}
